# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/c_accum_0/c_accum_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_accum_0 || ORIG_REF_NAME==c_accum_0} -quiet] -quiet

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0} -quiet] -quiet

# IP: ip/c_addsub_1/c_addsub_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_1 || ORIG_REF_NAME==c_addsub_1} -quiet] -quiet

# IP: ip/c_addsub_2/c_addsub_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_2 || ORIG_REF_NAME==c_addsub_2} -quiet] -quiet

# IP: ip/div_gen_0_1/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: ip/div_gen_1_1/div_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_1 || ORIG_REF_NAME==div_gen_1} -quiet] -quiet
